sudo: false
language: node_js
node_js:
    - 10
cache: npm
branches:
    only:
        - hexo-source
script:
    - 'hexo generate'
deploy: 
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    target_branch: master
    on: 
        branch: hexo-source
    local-dir: public
